# Site settings
title: Abhay Agarwal
twitter_username: abhayagarwal94
name: Abhay Agarwal

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Wordpress
   url: https://wordpress.com/view/ajourney870.wordpress.com
 - title: GitHub
   url: https://github.com/abhayagarwal94/
 - title: StackOverflow
   url: https://stackoverflow.com/users/9068576/abhay-agarwal
 - title: Medium
   url: https://medium.com/@abhayagarwal94
 - title: LinkedIn
   url: https://www.linkedin.com/in/abhay-agarwal06/

#Any buzzword skills you want to include
skills:
 - Python
 - Spark
 - Tableau
 - SQL
 - Machine learning
 - Data Visualization
 - Deep Learning
 - Product management
 - API design
 - Project Management
 - DJango/Flask MVC
 - SQL
 - REST
 - Technical Architecture
 

#Work experience is required
roles:
 - title: Digial Product Manager
   start: Nov'19
   end: Ongoing
   employer: Freelancer
   description: Giving consultancy services for digital product creation to management involving large scale data analysis. Product Designing, testing, releasing, post-release reponse analysis such as funnnel visualization, A/B testing for new features etc.
 - title: Data Analyst
   start: Jun'17
   end: Oct'19
   employer: Squareone Insights Pvt Ltd
   description: Initially, My role involved maintaining library of model documents, templates, other reusable knowledge assets as well as gather business requirements from digital innovation teams. Eventually, I started drafting analytical solution and implementation approaches for different business problems using different algorithms such as classification(Logistics Regression, DT, RF, Naive Bayes), Time-series analysis, clustering techniques etc.
 - title: Business Analyst
   start: Jul'16
   end: May'17
   employer: Loylty Rewardz Mngt Ltd
   description: Synthesize business insights to give recommendations for actionables. Analyze trends to identify potential market for new product to create new revenue sources. Identify  industry or geographic trends with business strategy implications. Manage timely flow of business intelligence information to users. Communication with different stackholders to stay abreast of industry
 - title: System Analyst
   start: May'16
   end: Jun'16
   employer: National Highway Authority of India
   description: I worked as an auditor to analyze the system before releasing it for production, submitted report to highlight flaws as well as future upgradation in the system.

#Education is required
education:
 - level: Bachelor of Technology (B.Tech.)
   date: Jun'16
   subject: Electrical Engineering
   school: Indian Institute of Technology, Kanpur

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/319126ad5de8e5417f5674c220f4044c
   courses:
    - title: Named Entity Recognition using LSTMs with Keras
      link: https://www.coursera.org/projects/named-entity-recognition-lstm-keras-tensorflow
      optionalimage: https://www.google.com/search?q=nlp&sxsrf=ALeKk019oEXEWoMNYiIHVUuH-lFq ywvZA:1590139868695&source=lnms&tbm=isch&sa=X&ved=2ahUKEwid4ZDQlMfpAhXSILcAHXmzD2EQ_AUoAnoECBoQBA#imgrc=W8RhX3QXvy3woM
      date: May	16, 2020

udemy:
   profileurl: https://www.udemy.com/user/piyush-garg-28/
   courses:
    - title: Python and django full stack web developer bootcamp
      link: https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp/
      optionalimage: https://www.google.com/search?q=django&tbm=isch&ved=2ahUKEwjn2seHmMfpAhWtMXIKHehdANoQ2-cCegQIABAA&oq=django&gs_lcp=CgNpbWcQAzIECCMQJzIECAAQQzIECAAQQzIECAAQQzIECAAQQzIECAAQQzIECAAQQzIECAAQQzICCAAyAggAUPQVWOUaYM0caABwAHgAgAGUAogB4QmSAQUwLjMuM5gBAKABAaoBC2d3cy13aXotaW1n&sclient=img&ei=dp_HXufHDq3jyAPou4HQDQ&bih=984&biw=1855#imgrc=5hpgJBY2ZPz19M
      date: May 21, 2020

#List of interesting Github repo/projects to include - optional
github:
 - abhayagarwal94/abhayagarwal94.github.io
 - abhayagarwal94/Social-Interaction-WebApp
 - abhayagarwal94/Face-Similarity
 - abhayagarwal94/IoT-Data-Analytics
 - abhayagarwal94/LoanPrediction

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/9068576/abhay-agarwal
   flairimageurl: https://stackoverflow.com/users/flair/9068576.png

intro: |
  Proactive professional with 4 years of experience and a proven knowledge of programming and data analysis. Aiming to leverage my skills to generate actionable insights for businesses. <br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code. <br/><br/>
  I have done various analytics projects for different products and services with large Indian companies as well as start-ups. I have delivered projects by travelled to client sites as well as remotely (As per project requirements). Also, I started a software company to digitise the whole textile business processes on a single application.
